name: cd-workflow

on:
  push:
    branches:
      - main
      - feat/use-playwright
    tags:
      - v*.*.*

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output current package version
        id: package
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          echo "::set-output name=version::$VERSION"
      - name: Output current image tag of Playwright
        id: playwright
        run: |
          yarn install --frozen-lockfile
          VERSION=$(node -e 'console.log(require("playwright-core/package.json").version)')
          echo "::set-output name=image_tag::v${VERSION}-focal"
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/vivliostyle/cli
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            VS_CLI_VERSION=${{ steps.package.outputs.version }}
            PLAYWRIGHT_TAG=${{ steps.playwright.outputs.image_tag }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
