name: test

on:
  - push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Install external library
        run: sudo apt-get update && sudo apt-get install -y ghostscript poppler-utils
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn test
  build-and-push-image:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
      - name: Output current package version
        id: package
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          echo "::set-output name=version::$VERSION"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            VS_CLI_VERSION=${{ steps.package.outputs.version }}
          tags: localhost:5000/vivliostyle/cli:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/vivliostyle/cli:latest
